# .readthedocs.yml (Corrected PDF Compilation)
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # 1. Installation commands (OK)
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    
    # 2. Build the HTML documentation (OK)
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
      
    # 3. Build the LaTeX source files (OK)
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/latex

    # 4. Compile the PDF from LaTeX and move it to the final destination
    
    # Change directory to where the LaTeX source files were placed
    - cd $READTHEDOCS_OUTPUT/latex
    
    # NEW FIX: Explicitly call the sphinx-build command to compile the PDF.
    # This uses the '-M latexpdf' argument, which is the command line equivalent
    # of running 'make latexpdf', ensuring the PDF is compiled.
    - >-
      .venv/bin/python -m sphinx.cmd.build -M latexpdf
      . _build

    # Move and rename the final PDF file to the location expected by RTD
    # The expected output name is SHAP.pdf (from your latex_documents in conf.py)
    # The final PDF must be placed in $READTHEDOCS_OUTPUT/pdf/ and named $READTHEDOCS_PROJECT.pdf
    - mkdir -p $READTHEDOCS_OUTPUT/pdf/
    # The compiled PDF will be in _build/latex/<master_doc>.pdf, which is SHAP.pdf
    - mv _build/latex/SHAP.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

# Specify the final output formats you want Read the Docs to make available
formats:
  - htmlzip
  - pdf
  - epub
