# .readthedocs.yml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # ADDED: System package to handle SVG conversion for LaTeX
  # This installs Inkscape, which provides the tools needed to convert SVGs to PDF
  apt_packages:
    - inkscape
    
  commands:
    # 1. Installation commands (OK)
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    
    # 2. Build the HTML documentation (OK)
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
      
    # 3. Build the LaTeX source files (OK)
    # The output is placed in $READTHEDOCS_OUTPUT/latex
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/latex

    # 4. Compile the PDF from LaTeX and move it to the final destination
    
    # NEW FIX: Change directory back to the project root.
    - cd $READTHEDOCS_OUTPUT/latex
    - cd ../../
    
    # Explicitly call the sphinx command to compile PDF.
    # Note: Sphinx handles the SVG conversion automatically if the tool (inkscape) is installed.
    - >-
      .venv/bin/python -m sphinx.cmd.build -M latexpdf
      docs _readthedocs
      
    # Move and rename the final PDF file to the location expected by RTD
    - mkdir -p $READTHEDOCS_OUTPUT/pdf/
    - mv _readthedocs/latex/SHAP.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

# Specify the final output formats you want Read the Docs to make available
formats:
  - htmlzip
  - pdf
  - epub
