# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # System package to handle SVG conversion for LaTeX
  apt_packages:
    - inkscape
    
  commands:
    # 1. Installation commands (OK)
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    
    # --- BUILD STEPS ---
    
    # 2. Build the HTML documentation
    # This must be run first to ensure all dependencies/extensions are loaded
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
      
    # 3. Build the LaTeX source files to a well-known LOCAL directory
    # We use a path relative to the project root, like '_latex_build',
    # where the Makefile is reliably created alongside SHAP.tex.
    - mkdir -p _latex_build
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs _latex_build

    # 4. Compile the PDF from the generated source
    
    # FIX: Change directory directly into the LOCAL build folder.
    - cd _latex_build
    
    # Execute the Makefile to compile SHAP.tex into SHAP.pdf.
    # The 'make' utility is run in the same folder as the Makefile and SHAP.tex.
    - make

    # 5. Move and rename the final PDF file for Read the Docs to find
    
    # Change back to project root
    - cd ..
    
    # Move and rename the final PDF file from the local build folder
    - mkdir -p $READTHEDOCS_OUTPUT/pdf/
    # The compiled file is now found at: _latex_build/SHAP.pdf
    - mv _latex_build/SHAP.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

formats:
  - htmlzip
  - pdf
  - epub
