version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # cf. https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    # Build HTML documentation (kept from original)
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
    # Build LaTeX documentation
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/latex

# Specify the output formats, including pdf
formats:
  - html
  - pdf
  # latex is also built but pdf is usually the desired output for users

# If you only build latex, Read the Docs will automatically compile it to PDF.
# Since you have custom commands, it's safer to ensure all dependencies for PDF
# generation are available, which Read the Docs handles for the 'pdf' format.
# When using custom commands, Read the Docs looks for a file named
# <project>.pdf inside $READTHEDOCS_OUTPUT/pdf/ (or similar) but usually
# handles the final step if 'latex' is built into $READTHEDOCS_OUTPUT/latex.
# The default build process for PDF is:
# 1. Build LaTeX: sphinx -b latex ... $READTHEDOCS_OUTPUT/latex
# 2. Compile PDF: cd $READTHEDOCS_OUTPUT/latex && make all-pdf
#
# By specifying 'formats: [..., pdf]' and building the 'latex' format,
# Read the Docs should take care of the final PDF compilation step.
# If you must control the compilation, you could add:
# - cd $READTHEDOCS_OUTPUT/latex
# - make all-pdf
# but relying on the 'formats' option is the standard, simpler way.
