# .readthedocs.yml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # 1. Installation commands (These were OK)
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    
    # 2. Build the HTML documentation (These were OK)
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
      
    # 3. Build the LaTeX source files (These were OK)
    # The output is placed in $READTHEDOCS_OUTPUT/latex
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/latex

    # 4. Compile the PDF from LaTeX and move it to the final destination
    
    # NEW FIX: Change directory back to the project root.
    # We must be at the root to find the 'docs' source directory and 'conf.py'.
    - cd $READTHEDOCS_OUTPUT/latex
    - cd ../../
    
    # Explicitly call the sphinx command to compile PDF.
    # Run from the root, pointing to 'docs' as source and '_readthedocs' as a temporary build dir.
    - >-
      .venv/bin/python -m sphinx.cmd.build -M latexpdf
      docs _readthedocs
      
    # Move and rename the final PDF file to the location expected by RTD
    # The compiled file is now found at the new temporary build path: _readthedocs/latex/SHAP.pdf
    - mkdir -p $READTHEDOCS_OUTPUT/pdf/
    - mv _readthedocs/latex/SHAP.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

# Specify the final output formats you want Read the Docs to make available
formats:
  - htmlzip
  - pdf
  - epub
