# .readthedocs.yml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # System package to handle SVG conversion for LaTeX
  apt_packages:
    - inkscape
    
  commands:
    # 1. Installation commands (OK)
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    
    # 2. Build the HTML documentation (OK)
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
      
    # 3. Build the LaTeX source files (Creates SHAP.tex and the Makefile)
    # Target a build directory *inside* the project root (e.g., _build/latex)
    # We MUST use the Sphinx command from the root folder to correctly pick up conf.py
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs _build/latex

    # 4. Compile the PDF from LaTeX and move it to the final destination
    
    # FIX: Change directory to the locally created latex build directory.
    - cd _build/latex
    # Use the local Makefile to compile the PDF.
    - make

    # Move the final PDF file to the location expected by RTD
    - mkdir -p $READTHEDOCS_OUTPUT/pdf/
    - mv SHAP.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

# Specify the final output formats you want Read the Docs to make available
formats:
  - htmlzip
  - pdf
  - epub
