version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # cf. https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install -r docs/requirements-docs.txt
    - uv pip install setuptools cython
    - .venv/bin/python setup.py build_ext --inplace
    # Build HTML documentation (kept from original)
    - >-
      .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/html
    # Build LaTeX documentation (necessary for PDF output)
    - >-
      .venv/bin/python -m sphinx -T -b latex -d docs/_build/doctrees -D language=en
      docs $READTHEDOCS_OUTPUT/latex

# Specify the output formats as a YAML list
formats:
  - htmlzip # Read the Docs default for HTML downloads
  - pdf       # Request PDF output
  - epub      # Optional: Request EPUB output (ebook format)
